# Generated by Django 5.2.4 on 2025-08-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Employer", "Employer")],
                max_length=20,
            ),
        ),
    ]
